title: Willaford Consulting
description: "Consulting services for .NET, SQL optimization, and legacy modernization."
baseurl: "" # keep this empty unless the site is in a subfolder
url: "https://willafordconsulting.com/"

# Theme (choose one of GitHub Pages supported themes)
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
